### ISSUE TITLE
Browser Action tool does not work in Linux devcontainer on Apple Silicon Mac

### ISSUE THREAD

**Issue by preritdas** [cline/cline#664] opened 2024-10-31 21:37 UTC
### Which API Provider are you using?

Anthropic

### Which Model are you using?

Claude 3.5 Sonnet

### What happened?

Cline isn't able to use Puppeteer when requested inside of a Linux devcontainer on an Apple Silicon Mac. 

```bash
Error executing browser action:
Failed to launch the browser process!
rosetta error: failed to open elf at /lib64/ld-linux-x86-64.so.2
```

![CleanShot 2024-10-31 at 17 36 04@2x](https://github.com/user-attachments/assets/826be2f5-0502-4f6f-9a2d-fd7314f3b7e9)

### Steps to reproduce

1. Open a folder/repo in container volume (I use Python bullseye images, ex. `python:3.12-bullseye`)
2. Ask Cline to use a browser

### Relevant API REQUEST output

```shell
Error executing browser action:
Failed to launch the browser process!
rosetta error: failed to open elf at /lib64/ld-linux-x86-64.so.2
```

**Comment by saoudrizwan** [comment] 2024-11-08 01:26
Thanks for reporting! Closing as duplicate of https://github.com/cline/cline/issues/668

**Closed by saoudrizwan** 2024-11-08 01:26 UTC
Labels: bug

**Comment by santicalcagno** [comment] 2024-11-08 09:26
@saoudrizwan I don't think this is related to #668. From what I gather this has to do with the fact that puppeteer doesn't have arm64 binaries for chromium, see https://github.com/puppeteer/puppeteer/issues/7740#issuecomment-2232605280.

Would you be open to accept a PR that switches from puppeteer to playwright for the browser action?

**Comment by chriopter** [comment] 2025-01-03 17:39
Same for me; I tried to install chromium in a dev container and point puppeteer to it, but it seems to ignore PUPPETEER_EXECUTABLE_PATH.

**Comment by chriopter** [comment] 2025-01-03 18:22
Temporary fix for me is to install rosetta and pull the amd64 image; e.g.

> FROM --platform=linux/amd64 ghcr.io/rails/devcontainer/images/ruby:$RUBY_VERSION

**Comment by preritdas** [comment] 2025-01-03 18:25
> Temporary fix for me is to install rosetta and pull the amd64 image; e.g.
> 
> > FROM --platform=linux/amd64 ghcr.io/rails/devcontainer/images/ruby:$RUBY_VERSION
> 
> @preritdas

Interesting... Thanks for sharing! @chriopter
