### ISSUE TITLE
Mistral API doesn't work with openai compatible provider

### ISSUE THREAD

**Issue by birdup000** [cline/cline#938] opened 2024-12-17 19:27 UTC
### Which API Provider are you using?

OpenAI Compatible

### Which Model are you using?

mistral-large-latest

### What happened?

When I enter the base uri for mistral this one ```https://api.mistral.ai/v1``` specify that model and enter the api key it doesn't work I get error 401 status code (no body)

### Steps to reproduce

1. Enter Api uri for Mistral
2.enter the model and key
3.start a task and error will show

**Comment by saoudrizwan** [comment] 2024-12-25 23:27
Closing as duplicate of https://github.com/cline/cline/issues/939

**Closed by saoudrizwan** 2024-12-25 23:27 UTC
Labels: bug

**Comment by Dharmesh946** [comment] 2026-09-02 09:08
I also got many
DeprecationWarning: AI SDK Warning (openai-compatible.chat / mistralai-medium): Deprecated: "providerOptions key 'openai-compatible'". Use 'openaiCompatible' instead.

simultaneously, cline stalles and got Cannot connect to API: other side closed: SocketError: other side closed (UND_ERR_SOCKET)

since 2 weeks I would say
(cline v4.1.16, mistral medium 3.5)
