### ISSUE TITLE
API Request failing with "[GoogleGenerativeAI Error]: Error fetching from..."

### ISSUE THREAD

**Issue by telegraph-pole-head** [cline/cline#936] opened 2024-12-17 14:20 UTC
### Which API Provider are you using?

Google Gemini

### Which Model are you using?

Gemini 2.0 Flash Experimental

### What happened?

Can't use gemini, getting error:

```json
{
  "error": {
    "message": "[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:streamGenerateContent?alt=sse: [400 ] * GenerateContentRequest.tools[0].function_declarations[0].parameters.required[0]: property is not defined\n"
  },
  "provider": "google"
}
```

### Steps to reproduce

1. use api key from google ai studio
2. just chat
3.

### Relevant API REQUEST output

```shell
{
  "error": {
    "message": "[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:streamGenerateContent?alt=sse: [400 ] * GenerateContentRequest.tools[0].function_declarations[0].parameters.required[0]: property is not defined\n"
  },
  "provider": "google"
}
```

**Comment by Huge** [comment] 2024-12-21 18:56
hey @saoudrizwan , seems there is no `cline version` field in the [bug form](https://github.com/cline/cline/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml), perhaps worth adding to make debugging process less confusing.

**Comment by nikolaidk** [comment] 2024-12-23 13:23
Had same issue. I created a key in google ai studio and added it to https://openrouter.ai/settings/integrations then everything started working  :)

**Comment by xiangnanscu** [comment] 2024-12-25 01:53
same error:
![image](https://github.com/user-attachments/assets/1ba58996-e130-43e9-9eb8-4eb04758d42c)

**Comment by saoudrizwan** [comment] 2024-12-25 23:32
@Huge just added, good idea!

**Comment by saoudrizwan** [comment] 2024-12-25 23:33
We'll need to look at the response and show a more user friendly error message.

**Comment by saoudrizwan** [comment] 2024-12-25 23:40
Closing as duplicate of https://github.com/cline/cline/issues/937

**Closed by saoudrizwan** 2024-12-25 23:40 UTC
Labels: bug, help wanted, good first issue
