### ISSUE TITLE
saoudrizwan.claude-dev extension not connecting to local mcp-gsuite server

### ISSUE THREAD

**Issue by giannis88** [cline/cline#987] opened 2024-12-22 09:06 UTC
### What happened?

I am experiencing an issue where the saoudrizwan.claude-dev extension in VS Code is not connecting to a locally running mcp-gsuite server. I have followed the instructions in the mcp-gsuite README to set up the server and obtain a refresh token.

### Steps to reproduce

Steps I have taken:

Created a Google Cloud project and enabled the Gmail API and Calendar API.
Configured OAuth consent screen and created OAuth 2.0 Client ID credentials.
Downloaded the credentials as credentials.json and placed it in the mcp-gsuite directory.
Used get-refresh-token.mjs to obtain a refresh token, which I added to cline_mcp_settings.json.
Set GSUITE_CLIENT_ID and GSUITE_CLIENT_SECRET as system environment variables in Windows.
Confirmed that the environment variables are correctly set by using echo %GSUITE_CLIENT_ID% and echo %GSUITE_CLIENT_SECRET% in the Command Prompt.
Started the gsuite-server.mjs using node gsuite-server.mjs.
Confirmed that the server is running and can be accessed using curl http://localhost:3000/listGmailMessages, which returns a valid JSON response.
Tried to use the listGmailMessages and listCalendarEvents tools within the saoudrizwan.claude-dev extension in VS Code.

### Additional context

Expected behavior:

The saoudrizwan.claude-dev extension should connect to the mcp-gsuite server and successfully execute the listGmailMessages and listCalendarEvents tools.

Actual behavior:

The extension is not connecting to the server. When I try to use the tools, I get the error message: "MCP error -2: Request timed out". The server logs show that the server is not receiving any requests from the extension.

Additional information:

The gsuite-server.mjs logs show that the server is picking up the correct GSUITE_CLIENT_ID and GSUITE_CLIENT_SECRET values from the system environment variables.
The curl tests confirm that the server is working independently and can communicate with the Gmail API.
The issue seems to be specific to the saoudrizwan.claude-dev extension.
I have examined the extension settings in VS Code, but there are no settings related to configuring local MCP servers.
I have enabled debug mode in the extension settings, but I haven't been able to find any relevant logs in the VS Code "Output" panel.
Questions for the developer:

Does the saoudrizwan.claude-dev extension support connecting to local MCP servers like mcp-gsuite?
If so, how can I configure the extension to connect to a server running on localhost:3000?
How does the extension handle environment variables for MCP servers?
Is there a way to enable more detailed logging for debugging connection issues?
Is there a recommended way to use local services or tools with the extension, even if it doesn't directly support MCP?
Does the extension have any mechanisms for defining custom actions or commands that could potentially be used to interact with a local server?
Are there any plans to add support for local MCP servers in the future?

**Comment by saoudrizwan** [comment] 2024-12-25 22:39
Closing as duplicate of https://github.com/cline/cline/issues/1029

**Closed by saoudrizwan** 2024-12-25 22:39 UTC
Labels: bug
