### ISSUE TITLE
Unable to use headless browser to open @url mentions

### ISSUE THREAD

**Issue by Pixxel123** [cline/cline#517] opened 2024-10-13 00:39 UTC
### Which API Provider are you using?

Anthropic

### Which Model are you using?

Claude 3.5 Sonnet

### What happened?

I've attempted to fetch docs from `@https://coreui.io/angular/docs/components/smart-table/#smarttable-module`

But I always get the error:

```
Error fetching content for https://coreui.io/angular/docs/components/smart-table/#smarttable-module: Failed to launch the browser process!
/home/mark/.vscode-server/data/User/globalStorage/saoudrizwan.claude-dev/puppeteer/.chromium-browser-snapshots/chromium/linux-1358568/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://pptr.dev/troubleshooting
```

I am using Windows, with an Ubuntu WSL2 remote server in VSCode.

```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

### Steps to reproduce

1. Open VSCode.
2. Ask Cline to parse any link.
3. Error occurs.

**Comment by lord-dubious** [comment] 2024-10-19 02:30
install puppeteer

**Comment by saoudrizwan** [comment] 2024-11-08 01:29
Closing as duplicate of https://github.com/cline/cline/issues/668

**Closed by saoudrizwan** 2024-11-08 01:29 UTC
Labels: bug
