### ISSUE TITLE
Cline Overwriting full code with # ... (keep the existing imports and other functions) and # ... (keep the rest of the file unchanged)

### ISSUE THREAD

**Issue by FoxRedRisk** [cline/cline#534] opened 2024-10-14 09:27 UTC
### Which API Provider are you using?

Anthropic

### Which Model are you using?

Sonnet

### What happened?

Cline is accepting and then overwriting full functional code (that has taken hours to get write) with insert snippets such as the one below:

# ... (keep the rest of the file unchanged)
# ... (keep the existing imports and other functions)

### Steps to reproduce

1. Prompt Cline
2. API called
3. LLM may or may not produce partial 'lazy' code.

### Relevant API REQUEST output

```shell
Aider has some functionality that prevents this from happening. It would be great if this could also be incorporated into Cline.
```

**Comment by iainRedro** [comment] 2024-10-14 13:07
This appears to have gotten worse and worse over the last few weeks.

**Comment by andatt** [comment] 2024-10-14 13:21
100% - it's gone from brilliant to barely useable for me because of this issue. Even after telling it not to do that in the custom instructions it continues to delete previously working code and replace with comments. Is this a cline issue or claude issue I wonder?

**Comment by tanushshukla** [comment] 2024-10-14 14:14
also, it removes all the comments from the file. I love this extension so much. I wish there is a way to improve this. I do add custom instructions to not remove my comments, but it still does it.

**Comment by HomeDev68** [comment] 2024-10-14 14:45
@andatt This is probably a claude issue and I have been experiencing it on Claude (Web version), Sonnet-3.5 often does this when it starts to get lazy inorder to Save it context window from being filled.

**Comment by tanushshukla** [comment] 2024-10-14 16:00
or manually copy from left to right, save and then accept.

**Comment by iainRedro** [comment] 2024-10-14 17:19
I have reverted to version 1.9.4 and my, entirely subjective, feeling is that this is not doing it as much any more. Claude API has a 8192 output token limit for Sonnet 3.5, which isn't dictated by input token count. So it shouldn't be chopping my 4k output because of such limitation I don't think. I'll stick with 1.9.4 until either I am proven wrong or stable improves.

Excellent project though! Great work.

**Comment by andatt** [comment] 2024-10-15 17:35
I have downgraded to 1.9.7 and the issue seems to be resolved. So it does seem to be cline issue . Has something changed in cline between these two versions that could affect they way comments which delete code are processed?

**Comment by iainRedro** [comment] 2024-10-15 17:42
I asked Claude how to create a framework for getting an LLM to suggest code changes using a JSON structure which could then be used by a tool to intelligently make the changes based on the instructions instead of writing entire code. Saves tokens..might be smart. Haven't got capacity to contribute..sorry! It suggested the below as a design and then a prompt.
---- DESIGN ----
{
  "version": "1.0",
  "file_changes": [
    {
      "file_path": "path/to/file1.py",
      "operations": []
    },
    {
      "file_path": "path/to/file2.py",
      "operations": []
    }
  ]
}

Specific example:

{
  "type": "add|delete|modify",
  "context": {
    "before": ["line before", "..."],
    "after": ["line after", "..."]
  },
  "content": ["new line 1", "new line 2", "..."]
}

Increasing complexity:

{
  "type": "add|delete|modify",
  "context": {
    "before": ["line -3", "line -2", "line -1"],
    "after": ["line +1", "line +2", "line +3"],
    "offset": 0,
    "uniqueness_radius": 10
  },
  "content": ["new line 1", "new line 2", "..."]
}

{
  "type": "add",
  "context": {...},
  "content": ["new line 1", "new line 2"]
}

{
  "type": "delete",
  "context": {...},
  "count": 2
}

{
  "type": "modify",
  "context": {...},
  "content": ["modified line 1", "modified line 2"],
  "count": 2
}

Execute all file actions in sequence.

---- PROMPT ----

Given the following code snippet:

[INSERT CODE SNIPPET HERE]

1. Analyze the code and suggest improvements or changes. Consider factors such as:
   - Code efficiency
   - Readability
   - Best practices
   - Potential bugs or edge cases

2. For each suggested change, provide:
   - A brief explanation of why the change is beneficial
   - The expected impact on the code's functionality or performance

3. Format your suggested changes using the following JSON structure:

{
  "version": "1.1",
  "file_changes": [
    {
      "file_path": "[SPECIFY FILE PATH]",
      "operations": [
        {
          "type": "[OPERATION TYPE]",
          "context": {
            "before": ["[LINES BEFORE CHANGE]"],
            "after": ["[LINES AFTER CHANGE]"]
          },
          "content": ["[NEW OR MODIFIED CODE]"],
          "comment": "[EXPLANATION FOR THIS CHANGE]"
        }
      ]
    }
  ],
  "impact_analysis": {
    "complexity_change": "[ESTIMATED CHANGE IN COMPLEXITY]",
    "performance_impact": "[ESTIMATED PERFORMANCE IMPACT]",
    "affected_functions": ["[LIST OF AFFECTED FUNCTIONS]"]
  }
}

4. Consider and include any relevant additional features from our change management system, such as:
   - Dependency management
   - Style enforcement
   - Testing requirements
   - Documentation updates

5. If applicable, suggest a progressive rollout strategy for these changes.

Please provide your analysis, suggestions, and formatted change instructions based on this structure.

**Comment by nonsintetic** [comment] 2024-10-16 07:32
Maybe I'm crazy but it only seems to do this when the file it's working on is very long. I've never seen it do that on a small file. 

I'm sure there's some limit on how long its responses can be and I remember the service prompt for Claude includes something about keeping things short. 

Maybe Cline can interpret this kind of code and detect those sections and put the original code back. Shouldn't be too hard since it's followed by a bunch of removed lines and the thing it says seem to be pretty consistent.

**Comment by tayls1544** [comment] 2024-10-16 14:02
I've been using this plugin for a few months now and absolutely love it, but I'm experiencing a similar issue. My app was fully functional, but I encountered a scrolling problem on the profile page. I asked Cline to resolve this issue, it ended up removing all the all the features, styling from my profile page, and I haven't been able to restore it to its original state. It's not a major problem as i'll just create it again, but I’m concerned it could lead to bigger issues down the line. I also included custom instructions to prevent this, but it didn't seem to work either. Brilliant if this can be addressed.

**Comment by saoudrizwan** [comment] 2024-10-16 22:34
The lazy coding issue is annoying, I'm sorry you guys are dealing with it. I put together this troubleshooting doc to help you work around it: https://github.com/cline/cline/wiki/Troubleshooting-%E2%80%90-Cline-Deleting-Code-with-%22Rest-of-Code-Here%22-Comments (tl;dr you can revert the placeholders in the diff view editor and/or copy paste the parts cline removed). Anthropic should be releasing their new fast edit mode soon that will make this problem a thing of the past, it will let the model spit out tokens its read before much more quickly and reliably (hopefully cheaper too?)

I've also just released v2.0.9 that modifies the system prompt to hopefully get Cline to do less lazy coding, so please give that a try and see how it works for you.

**Comment by drwbns** [comment] 2024-10-17 17:08
I'm updated to 2.0.11 and it still happens for me. It's causing about double the usage for me or more to have to direct Cline to fix what it removed. I've tried to give it an early prompt such as "make a list of a file's functions before editing and double check that they are all there after editing for any future edits." every so often, which seems to help.

**Comment by markwylde** [comment] 2024-10-17 19:54
Would it be possible to run each response via a cheap llama 3.2 model saying something like:

```
Claude has suggested we change test.tsx with the following:

---
...(keep existing code)
doSomething()
---

This is the existing file:

---
import ....
---

Make the changes then reply with the full file
```

The faster/cheaper models should be able to handle the request, since Claude would still be doing the hard part.

**Comment by AlexNodex** [comment] 2024-10-18 09:48
+1, been getting gradually worse over the last few days, to the point where you have to watch every single line it's making red and expand the other side to get the code back in...

Nearly lost a lot of code due to this a few times!

**Comment by saoudrizwan** [comment] 2024-10-18 13:00
There's been an increase in reports about this so I've made the following changes in the latest v2.0.15 that should help mitigate the issue:
1. Adjusted system prompt to keep Cline from doing this as much as possible, but for large enough files it's impossible to force him to output beyond the model's max output token limit. I found that trying to keep him from lazy coding too aggressively would lead to him outputting partial file contents. 
2. When Cline does truncate code you are now alerted by the extension of 'potential code truncation' along with a link to a [troubleshooting guide](https://github.com/cline/cline/wiki/Troubleshooting-%E2%80%90-Cline-Deleting-Code-with-%22Rest-of-Code-Here%22-Comments) to work around the issue. This way you don't accidentally approve an edit with truncation. 
3. The guide essentially walks you through how to use the diff editor to replace the placeholder comments with the original content. I've also improved the prompts around this so that the model is made aware that the user fixed its response and to proceed accordingly with the new file contents as the baseline.

As soon as the new fast edit mode feature is available I will be updating the extension with it, thank you for your patience guys.

**Comment by andatt** [comment] 2024-10-18 16:16
Thanks for you response and work on this!

**Comment by yaleh** [comment] 2024-10-18 23:20
> Would it be possible to run each response via a cheap llama 3.2 model saying something like:
> 
> <img alt="Screenshot 2024-10-17 at 21 00 37" width="795" src="https://private-user-images.githubusercontent.com/5929807/377616612-3d2ec2da-ad4e-498e-b7f5-21a0993df61c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyOTM3NzMsIm5iZiI6MTcyOTI5MzQ3MywicGF0aCI6Ii81OTI5ODA3LzM3NzYxNjYxMi0zZDJlYzJkYS1hZDRlLTQ5OGUtYjdmNS0yMWEwOTkzZGY2MWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMThUMjMxNzUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGI3YzRjYmJlMzMwYzg2MTU5NjA2MmQyNmYwZjlhOTA0YjdiZDcxNmVkZTM4NWMzNDZmNDllMGZkZWIxZmY1MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.tRsdvfIMjPuXw9_Zc_GtcXbfOBZdbh4kA7jD8Xw7TYE">
> The faster/cheaper models should be able to handle the request, since Claude would still be doing the hard part.

Yes. I believe Cursor is using something similar, patching the generated code back with a smaller model.

**Comment by stevejford** [comment] 2024-10-19 01:45
Is it possible to create agents one that maintains the origanal code and
one thatchecks and tests the code and one for editing. I believe breaking
it up into smaller tasks would be more beneficial and allows a much larger
token size.

**Comment by elogicuk** [comment] 2024-11-01 09:54
This issue is still happening a lot today

**Comment by hellosg** [comment] 2024-11-06 12:58
Like everyone I've been having this issue with Claude 3.5 (via Anthropic or OpenRouter).

I ended up with 5 or so files that were quite large and were all having this issue repeatedly.

So I prompted via Cline along the lines of:

> What are the remaining changes needed for this task? Can you try generating a patch file and running that in the terminal for one of the file?
> We've been having issues with you editing large files where lots of code is lost
> Maybe if we try a patch file and command, just making the specific required changes, this might work? Make sure you create a separate patch file for each file that needs editing

Cline agreed it was a great idea, and proceeded to create a patch file, apply it via a command in the terminal, which worked.

![image](https://github.com/user-attachments/assets/0bdb85f1-9075-464b-ba5c-efbf9d666364)

And then it moved onto a patch for the next file, and so on.

This works for me as a temporary workaround until we get Anthropic's Fast Edit Mode

**Comment by saoudrizwan** [comment] 2024-11-08 02:12
OpenAI just released a new API featured called [predicted outputs](https://platform.openai.com/docs/guides/latency-optimization#use-predicted-outputs) that would fix this issue entirely. It essentially spits out the tokens its read before and only has to "think" about new tokens (the new edits to the file), making the edit faster and more reliable without the code truncation. The issue is that this API is very rudimentary and limited (doesn't allow images, only works with gpt4o, etc) so it doesn't fit as nicely into Cline as I'd like. I'm hoping Anthropic comes out with their version of this API soon (which they've pre-released in Zed, called [Fast Edit Mode](https://www.youtube.com/watch?v=6CCuyTMhZKw)), so I can add it to Cline ASAP and fix this problem.

Pls join the [discord](https://discord.gg/cline) for updates about this, and thank you for bearing with me in the meantime 🙏

**Closed by saoudrizwan** 2024-11-08 02:12 UTC
Labels: bug
