### ISSUE TITLE
Approved code changes to files deletes rest of unchanged code

### ISSUE THREAD

**Issue by odebroqueville** [cline/cline#625] opened 2024-10-26 19:08 UTC
### Which API Provider are you using?

Anthropic

### Which Model are you using?

Claude 3.5 Sonnet

### What happened?

I copy-pasted a portion of the code in a file concerning keyboard input and gave a short explanation of the problem encountered. Cline proposed some code changes which I had to approve. It was not clear to me if the area in red (which included the majority of the code which should be left unchanged) would remain unchanged or be deleted. It all ended up being deleted which clearly shouldn't happen. It's happened to me twice already and the first time around I lost all the changes I had made to a file that hadn't been committed. Besides that, I lost a lot of time to correct things and it has also cost me.

### Steps to reproduce

1. I was using code for a web extension, but I guess this would happen with any code with multiple files
2. I just tried to debug a section of code that wasn't working as expected
3. Code changes had to be approved and the changes were applied. However, the all the code that didn't require any changes, in the file containing the section of code, got deleted.

### Additional context

![CleanShot 2024-10-26 at 20 32 17@2x](https://github.com/user-attachments/assets/f843d4ad-0301-4fea-ac54-25b272cfdbec)

[cline_task_oct-26-2024_8-33-58-pm.md](https://github.com/user-attachments/files/17531718/cline_task_oct-26-2024_8-33-58-pm.md)

**Comment by tluyben** [comment] 2024-10-27 07:56
Yes , this is a current issue and it is very annoying as it basically does it almost always the first request and then you reprompt it with something like "no, you removed everything from the file and thats wrong; never remove, only add and fix" and it works. But so now it costs me double the $ for the API basically. I'm playing with Haiku as well to ask it if something was removed and automatically reprompt; that's working too but obviously even more $! 

Also here; https://github.com/cline/cline/issues/596

**Comment by A-n-o-r-a-k** [comment] 2024-10-27 13:28
Yes, I just confirmed this is an issue as well. took a couple of tries to get it to roll back the code (revert) to its original form. maybe we can build a process that fills it in from a cached version on your local workstation and fills in when the response comes back. saving on token costs.

**Comment by tluyben** [comment] 2024-10-27 14:21
I have been trying to get sonnet to edit files instead of completely redo them; it works quite ok if we have a language parser and we can just have it replace/add/delete  functions and such. Asking it to delete line x to y and add code at position x would be nice but of course it has many issues counting. Trying to find other ways. My Go only version works well as it can parse, so it only generates and works with changes saving indeed in tokens.

**Comment by teetangh** [comment] 2024-10-27 14:34
I guess the new streaming behavior requires multiple undos to get back back to previous state. Requesting @saoudrizwan to  make the changes in a temporary preview file rather than the original file itself. When the changes are approved, they can be reverted with a single undo

**Comment by odebroqueville** [comment] 2024-10-27 16:11
@saoudrizwan First of all, thank you for Cline. I was first very impressed by what was possible with Cline. The issues encountered are serious, but I have a feeling that the fix shouldn't be too hard as Cline correctly identifies what changes in the code and what doesn't. In the mean time, I think that it's important for devs using Cline to ensure they have committed all code changes and synced with GitHub before using Cline to fix code issues. I would also recommend not using Cline to revert changes, but instead to discard changes in the Source Control tab.

**Comment by A-n-o-r-a-k** [comment] 2024-10-27 20:04
That is perfect. I need to be better at committing individual changes and
handling reverting through github or you can end up like me and run out of
tokens before getting it all back

Best Regards,
Garry Osborne
CEO Tomorrows Innovations, LLC
412-715-6504 cell
571-204-4836 work

**Comment by Garry-TI** [comment] 2024-10-28 10:54
I finally recoved my complete code. And then I spend a full day tracking down some interesting things. when I told Cline to recover the original code, along with taking multiple attempts, it changed some of the variable names in the index.html. one example was changing "genre" to "data-genre" in a bunch of tabs. syntactically the page would come up and run but none of the tabs functioned. This was because "genre" was not being set as a parameter for a fetch of data. So the data came back with all genre by default. 

Has anyone experienced variable changes unrelated to the area of code they were changing?
I was using claude 3.5 sonnet on the back end.

Best Regards,
Garry Osborne
CEO Tomorrows Innovations, LLC

**Comment by saoudrizwan** [comment] 2024-11-08 01:42
@odebroqueville @tluyben @A-n-o-r-a-k @teetangh I am sorry you guys are dealing with this.

OpenAI just released a new API featured called [predicted outputs](https://platform.openai.com/docs/guides/latency-optimization#use-predicted-outputs) that would fix this issue entirely. It essentially spits out the tokens its read before and only has to "think" about new tokens (the new edits to the file), making the edit faster and more reliable without the code truncation. The issue is that this API is very rudimentary and limited (doesn't allow images, only works with gpt4o, etc) so it doesn't fit as nicely into Cline as I'd like. I'm hoping Anthropic comes out with their version of this API soon (which they've pre-released in Zed, called [Fast Edit Mode](https://www.youtube.com/watch?v=6CCuyTMhZKw)), so I can add it to Cline ASAP and fix this problem.

Pls join the [discord](https://discord.gg/cline) for updates about this, and thank you for bearing with me in the meantime 🙏

**Closed by saoudrizwan** 2024-11-08 01:42 UTC
Labels: bug
