### ISSUE TITLE
Code gets corrupted/truncated. No workaround.

### ISSUE THREAD

**Issue by AIHypnosis** [cline/cline#577] opened 2024-10-20 15:41 UTC
### Which API Provider are you using?

Anthropic

### Which Model are you using?

Claude 3.5 

### What happened?

The issue is that the code get's corrupted/truncated very often. 
The whole blocks of code get deleted and substituted with comments like // ... (keep existing code).
In troubleshooting page it was offered to use Revert Block Button. This never worked. I click on Revert button but the code is not being reverted.
The issue is sporadic and not consistent. My file is not large, only 350 lines.  

### Steps to reproduce

1. Use Cline

**Comment by agent1red** [comment] 2024-10-26 14:08
This has become a real pain to work with. Some work arounds that I have done were to split large files up to smaller code files for easier management. Sometimes prompting claude to not remove code that isn't being refactored works.

**Comment by alreadyarrived** [comment] 2024-10-29 06:11
ugh i'm also facing the same problem. I just waste more tokens prompting 'don't truncate' and it fixes it

**Comment by jmartsch** [comment] 2024-10-31 18:48
Please take a look at this WIKI entry for possible fixes https://github.com/cline/cline/wiki/Troubleshooting-‐-Cline-Deleting-Code-with-"Rest-of-Code-Here"-Comments

**Comment by saoudrizwan** [comment] 2024-11-08 02:11
I am so sorry you guys are dealing with this.

OpenAI just released a new API featured called [predicted outputs](https://platform.openai.com/docs/guides/latency-optimization#use-predicted-outputs) that would fix this issue entirely. It essentially spits out the tokens its read before and only has to "think" about new tokens (the new edits to the file), making the edit faster and more reliable without the code truncation. The issue is that this API is very rudimentary and limited (doesn't allow images, only works with gpt4o, etc) so it doesn't fit as nicely into Cline as I'd like. I'm hoping Anthropic comes out with their version of this API soon (which they've pre-released in Zed, called [Fast Edit Mode](https://www.youtube.com/watch?v=6CCuyTMhZKw)), so I can add it to Cline ASAP and fix this problem.

Pls join the [discord](https://discord.gg/cline) for updates about this, and thank you for bearing with me in the meantime 🙏

**Closed by saoudrizwan** 2024-11-08 02:11 UTC
Labels: bug
