### ISSUE TITLE
Pull back the new version man. bot logic is straight up broken. 

### ISSUE THREAD

**Issue by sid-newby** [cline/cline#495] opened 2024-10-10 18:35 UTC
### Which API Provider are you using?

Anthropic

### Which Model are you using?

vertex, normal anthropic, 4o, all bad bad bad 

### What happened?

crazy haphazard removal of giant swaths of code, bugs with VSCode and the diff tools, continuous repeating of trying to delete 90% of project files, worked in Python, JavaScript, Node, and TypeScript. Everything I've worked on for the last 24 hours has been absolutely fucked.

Please be aware that things are very, very bad. Congratulations for an aggressive move forward. I love everything that you've done with the project, and I understand that this was a big change. But it's a step in the right direction. The accuracy has completely fallen off. I don't know what controls it, but you gotta know as well as I do at this point, man, this is very, very bad. No one should use it, straight up.

I don't need to give you all these cases and things like 'cause it's, if you give me a place to upload to, I can send you my contacts from the past 12 hours and show you everything I've been through. It's an absolute nightmare. Absolute nightmare. I'm glad to share it with you. 100% code, everything that's in there. Absolutely. You can have it, but if you've been using it, you know what I'm talking about. 

### Steps to reproduce

1. use
2. the
3. product

### Relevant API REQUEST output

```shell
If you give me a place to upload, man, I'll sanitize my keys and you can take a look at everything that I've done. I'm telling you. But you know, you know at this point, I'm sure you have another version coming out like real soon. But damn.
```

**Comment by hungle816** [comment] 2024-10-10 19:05
I agree with this. Since the update, claudeDev has been in a loop and fixes the issues but has created a bug in the process. When it tries to fix the new bug, it creates the same code it created that was modified.

It has been horrible, I understand saving cutting the API call but it feels like it is lacking some context.

**Comment by scottmraz** [comment] 2024-10-10 19:52
CLI access isn't working as noted in another thread as well.

**Comment by saoudrizwan** [comment] 2024-10-10 20:10
@sid-newby @hungle816 sorry to hear you guys had bad experiences. There's a lot of users that are on the other end of the spectrum and are having much better results with the new update, so it's hard for me to know exactly what to "fix" without getting more details about your specific use case. Testing big changes with ClaudeDev/Cline is hard because people use the extension in so many different ways/projects/stacks/custom prompts, so please bear with me while I improve the system/tool prompts to work better for you.

Feel free to DM me on discord (saoudrizwan) with your task export if you don't want to share it here.

**Comment by scottmraz** [comment] 2024-10-10 20:48
Tested and it seems like it's related to MacOS 15.0.1 everything seems broken w/ CLINE / ClaudDev - with any version. At least no terminal access for sure. On my MacOS 14.7 everything works fine.

**Comment by hungle816** [comment] 2024-10-10 22:18
I echo @scottmraz comment about 15.0.1. ClaudeDev is not reading the terminal

**Comment by saoudrizwan** [comment] 2024-10-11 01:59
@scottmraz @hungle816 Okay let's take make [this issue](https://github.com/clinebot/cline/issues/484) dedicated to the macos 15.0.1 terminal issues. 

@sid-newby Can you pls reach out to me on discord so we can figure out what exactly went wrong with your tasks? It helps knowing what your prompt was, what the model tried to do, where he went wrong, etc.

**Comment by jiriklic** [comment] 2024-10-11 09:17
I had the same negative experience since I upgraded to 2.0.

I would suggest to check the impact of going from batch to streaming. I personally find the new streaming animation feature a bit distracting anyway, and I hope it will be allowed in future versions to be toggled off.

However, it seems that streaming can have a negative impact on reasing quality too:

* Limited Planning: Streaming limits the model's ability to plan the full response, which can affect the logical flow and coherence.

* Reduced Accuracy: Without the opportunity to internally verify and correct reasoning steps before output, the model may produce errors that it cannot rectify in subsequent tokens.

* Interruption of Thought Process: Streaming can disrupt the model's internal chain-of-thought, leading to incomplete or fragmented reasoning.

In the meantime, I found the best help in #491

Solution: got to Extensions->Cline-> right click -> Install Specific Version -> 1.9.7

**Comment by saoudrizwan** [comment] 2024-10-11 14:27
@jiriklic there is no difference in the model's response whether it's streamed or not, so it wouldnt affect planning or accuracy or thought process, it still does all that before editing files. 

Can you please share the bad experience you had? The prompt you used, what cline did wrong, etc. Any details would be useful in helping me adjust the system/tool prompt to work better for wider use cases. It's hard for me to test every possible way people use the extension, and Ive heard a lot of users are having good experiences with the new update so I wouldnt know what to fix without more insight into what went wrong for you. Any help here is appreciated.

**Comment by jiriklic** [comment] 2024-10-11 15:29
> Can you please share the bad experience you had? The prompt you used, what Cline did wrong, etc. Any details would be useful in helping me adjust the system/tool prompt to work better for wider use cases. It's hard for me to test every possible way people use the extension, and Ive heard a lot of users are having good experiences with the new update so I wouldnt know what to fix without more insight into what went wrong for you. Any help here is appreciated.

@saoudrizwan - sure, no problem. My current prompt and workflow with Cline1.9.7 is as follows:

When I encounter an error in my code build (Python, C++ compiled binaries, build with Meson and cibuildwheel), I use the following prompt template:

```
Meson build failed with the following error:

` ` `
<I copy and paste the error from the terminal.>
` ` `

Please read the @/build/meson-logs/meson-log.txt and fix the issue. Keep all the comments.
```

Cline then asks me to read all the other relevant files it needs to solve the problem and finally asks me for permission to make the edits as necessary. I read/check each diff, save it if I think its is the right solution, and run the code. If everything works, I make Git commit and push the changes to the repository. BTW, I absolutely love this workflow. It increases my productivity by 5x-10x  as conservative estimate.

I use mainly Anthropic API with Claude 3.5 Sonnet.

When I upgraded to Cline 2.x, the response looked the same on the first impression. But the solution would create new errors, and when I prompted those in the same chat, the edit would just revert everything back to the state of the file as it was in the first place. I checked this with Git diff, so I am quite certain about this part. Therefore, the model would just get stuck in the infinite loop, making the same edit back and forth.

#### Why do I think that the new version of Cline and the streaming are the cause of this issue rather than the Claude 3.5 model itself:
After I downgraded back to Cline 1.9.7, everything started to work again as I am used to. All the edits since that point have been constructive and working solutions.

I hope it will help you in narrowing down the issue.

Please let me also use this opportunity to thank you for your great work. Cline 1.9.7 is an absolutely amazing development tool, and in combination with the Continue plugin, it beats by a mile any other tool on the market. 👍 

One last question: could you please make the new streaming feature optional in the Cline settings? That could smooth down the onboarding process of this new feature while not jeopardising workflow of your current users.

**Comment by saoudrizwan** [comment] 2024-10-13 04:05
>  and when I prompted those in the same chat, the edit would just revert everything back to the state of the file as it was in the first place. 

Gotchya, so the model is trying to edit the file with the same contents it tried to use before. This is in a nutshell *Claude being dumb* and not something that I could fix on the extension's part. Now why you're seeing different behavior in 1.9.7 seems totally subjective and could just be the luck of the draw. It would help if you updated to v2.0 and tried to ask Cline to do your task again and see if possibly rewording the prompt or course correcting more often through the task helps in getting the desired result. 

If you can create a reproducible instance where a given task is able to be accomplished in v1.9.7 and cannot be accomplished in v2.0, then please let me know/open a new ticket with your task exports–that could help me move things in the right direction.

Closing this ticket since there isn't anything I can fix here, other than improving the system/tool prompt to cover wider use cases which is already something I'm actively working on.

**Closed by saoudrizwan** 2024-10-13 04:05 UTC
Labels: bug
