### ISSUE TITLE
Cline doesn't work with Codestral from mistral.ai

### ISSUE THREAD

**Issue by gregid** [cline/cline#665] opened 2024-10-31 21:54 UTC
### Which API Provider are you using?

OpenAI Compatible

### Which Model are you using?

codestral/codestral-latest

### What happened?

I can't get codestral from mistral.ai to work with cline:
https://console.mistral.ai/codestral
(subscription - currently free to use)

### Steps to reproduce

1. Using for baseURL: `https://codestral.mistral.ai/v1/chat/completions`
2. Trying both `codestral/codestral-latest` and `codestral-latest` for model
3. Type a message

### Relevant API REQUEST output

```shell
404 status code (no body)
```

**Comment by saoudrizwan** [comment] 2024-11-01 03:46
Closing as duplicate of https://github.com/cline/cline/issues/582

**Closed by saoudrizwan** 2024-11-01 03:46 UTC
Labels: bug

**Comment by alfredwallace7** [comment] 2025-01-15 11:28
Please reopen as https://github.com/cline/cline/issues/582 does not provide a solution.
