### ISSUE TITLE
Long running tasks hang Cline

### ISSUE THREAD

**Issue by doodledood** [cline/cline#1052] opened 2024-12-27 10:08 UTC
### What happened?

Cline tried to run a "docker-compose up --build" command which took quite a while. It offered to "Proceed while waiting" but when I clicked I could not continue with the task (everything disabled). It seems the process didn't end properly as cline waited for it or something.

### Steps to reproduce

1. Have Cline run "docker-compose up --build"
2. Click proceed after a while 
3. Everything disabled

### Operating System

Mac

### Cline Version

3.0.6

**Comment by saoudrizwan** [comment] 2024-12-27 18:31
Thank you for reporting -- we recently updated workspace tracking to fix an unrelated bug, but that ended up causing any command that would modify a ton of files to cause vscode to lock up. This issue has been fixed in v3.0.7, pls feel free to re-open if you're still running into this

**Closed by saoudrizwan** 2024-12-27 18:31 UTC
Labels: bug

**Comment by doodledood** [comment] 2025-01-02 12:25
Hey unfortuantely it still happens. Completely hangs Cline (can't click any button).

Basically it tries to run a docker compose up for example and takes a long time. It is stuck on this.

![image](https://github.com/user-attachments/assets/4cd9be20-9d9f-44e2-b7ba-15ddb53564da)

Tried to click proceed, yet nothing happens

**Comment by soupdiver** [comment] 2025-04-27 03:11
Any insights here? @saoudrizwan 
The issue is closed but the problem still persists see #1404
