### ISSUE TITLE
code truncation on files that exceed 600 lines of code unable to edit goes around in circles and wastes tokens must be able to process and edit code in large files 

### ISSUE THREAD

**Issue by bob10042** [cline/cline#825] opened 2024-11-25 22:03 UTC
### Which API Provider are you using?

Anthropic

### Which Model are you using?

sonnet 3.5 new model

### What happened?

surley its not copying and pasting code snippets defeats the object of the app which at lower levels of code 500 lines or so performs okay but then the good old 429 errors and you have to start from scratch again need memory

### Steps to reproduce

1.
2.
3.

**Comment by saoudrizwan** [comment] 2024-11-27 01:10
OpenAI just released a new API featured called [predicted outputs](https://platform.openai.com/docs/guides/latency-optimization#use-predicted-outputs) that would fix this issue entirely. It essentially spits out the tokens its read before and only has to "think" about new tokens (the new edits to the file), making the edit faster and more reliable without the code truncation. The issue is that this API is very rudimentary and limited (doesn't allow images, only works with gpt4o, etc) so it doesn't fit as nicely into Cline as I'd like. I'm hoping Anthropic comes out with their version of this API soon (which they've pre-released in Zed, called [Fast Edit Mode](https://www.youtube.com/watch?v=6CCuyTMhZKw)), so I can add it to Cline ASAP and fix this problem.

Pls join the [discord](https://discord.gg/cline) for updates about this, and thank you for bearing with me in the meantime 🙏

**Closed by saoudrizwan** 2024-11-27 01:10 UTC
Labels: bug

**Comment by bob10042** [comment] 2024-11-27 08:50
Thanks A great product I think the best by far if you could let me know as soon as is available and what I have to do. I would gladly pay you for your time product it greatly speads productivity Many thanks for your prompt response Bob👌Sent from my iPhoneOn 27 Nov 2024, at 01:11, Saoud Rizwan ***@***.***> wrote:﻿
OpenAI just released a new API featured called predicted outputs that would fix this issue entirely. It essentially spits out the tokens its read before and only has to "think" about new tokens (the new edits to the file), making the edit faster and more reliable without the code truncation. The issue is that this API is very rudimentary and limited (doesn't allow images, only works with gpt4o, etc) so it doesn't fit as nicely into Cline as I'd like. I'm hoping Anthropic comes out with their version of this API soon (which they've pre-released in Zed, called Fast Edit Mode), so I can add it to Cline ASAP and fix this problem.
Pls join the discord for updates about this, and thank you for bearing with me in the meantime 🙏
