### ISSUE TITLE
fails to read @ directories and files in VSCode Remote SSH

### ISSUE THREAD

**Issue by Minidoracat** [cline/cline#587] opened 2024-10-21 23:50 UTC
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

Claude 3.5 Sonnet

### What happened?

When using the Visual Studio Code Remote SSH feature, the @ function in the cline plugin fails to list any directories or files. This issue only occurs when using Remote SSH; it does not appear in the local development environment. I have tried reinstalling the plugin and restarting the editor, but the issue persists.

Screenshots
Here are the screenshots showing the issue:

<img width="374" alt="image" src="https://github.com/user-attachments/assets/28ff2e93-a760-44ca-95cd-c27b76ef659f">

<img width="380" alt="image" src="https://github.com/user-attachments/assets/a6a2c8ff-1b0d-4bcc-9957-736d83c8442c">

### Steps to reproduce

1. Open a project using Visual Studio Code with Remote SSH connection.
2. Make sure the cline plugin is installed and activated.
3. Use the @ function in the project directory to list directories and files.
4. The result shows that no files or directories are found.

**Comment by saoudrizwan** [comment] 2024-12-26 00:22
Closing as duplicate of https://github.com/cline/cline/issues/933

**Closed by saoudrizwan** 2024-12-26 00:22 UTC
Labels: bug
