### ISSUE TITLE
How much of prompt caching is done not being Shown in the Extension while using Openrouter

### ISSUE THREAD

**Issue by birat-chapagain** [cline/cline#580] opened 2024-10-21 00:17 UTC
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

Sonnet-3.5

### What happened?

Its working fine just would be good if it shows how much prompt caching is being done in Openrouter  

### Steps to reproduce

1.You can just look into it
2.
![image](https://github.com/user-attachments/assets/e115fa4f-4505-4baa-9ab2-c8a08d66fe9a)

**Comment by nolanblew** [comment] 2024-11-01 21:25
I'm wondering if cache is even being utilized in OpenRouter. With medium sized web projects, Claude directly gives me a large cache and ~$0.20 per API request, while switching and using OpenRouter is sometimes ~$1.95 per API request

**Comment by bramblebrain** [comment] 2024-11-06 14:39
![image](https://github.com/user-attachments/assets/f8962681-44c1-4283-94bc-554590710101)

Open Router doesn't seem to be caching for me either, but it does cache when I directly use the api.

**Comment by birat-chapagain** [comment] 2024-11-06 14:55
My cost went like .3$ per api request and I had to stop my project

**Comment by bramblebrain** [comment] 2024-11-06 15:15
![image](https://github.com/user-attachments/assets/ca76ffb0-68c2-4aca-894b-7b81c75a177e)
Here is the prompt for both except for the change in filename:

1. Using Python create a Monte Carlo Simulation inside a file test2
2. Modify the code so that there is a screenshot of the monte carlo simulation
3. Modify the monte carlo simulation so that is for trading
4. Change the number of simulations to 100 and remove the axis on the graph

It doesn't appear to be using prompt caching at all

**Comment by anibalinbalin** [comment] 2024-11-07 13:40
I was wondering what was going on too. I spent 10 usd like nothing on openrouter. I think cache is not being used.

**Comment by ntrpnr** [comment] 2024-11-09 23:38
My findings confirms what you suspect - prompt caching is not being used with open router.
Each request is ~10x more expensive than with Anthropic's API for Sonnet 3.5, which is expected without prompt caching.

All activity items show this:
![image](https://github.com/user-attachments/assets/acc53308-72d2-47ce-86f7-c07c9dd42f87)

**Comment by nishantg96** [comment] 2024-11-10 19:56
@ntrpnr @saoudrizwan I can confirm that as of today prompt caching has stopped working with Openrouter. It was working completely fine yesterday. I dont see any particular updates since then - maybe something changed on openrouters end?

**Comment by ntrpnr** [comment] 2024-11-11 22:05
I've done some investigation and with some changes I've managed to get it to work. It seems however like the 3rd request (file shared) in a chat session causes API Request Failed: Provider returned error. I can't get around it.

**Comment by ntrpnr** [comment] 2024-11-12 00:22
@nishantg96 Feel free to check if my PR #716 fixes it for you

**Comment by ntrpnr** [comment] 2024-11-12 09:42
@nishantg96 Prompt caching is working for me on v2.1.4 for `anthropic/claude-3.5-sonnet:beta` but not for `anthropic/claude-3.5-sonnet`

**Comment by geocine** [comment] 2024-11-17 07:15
Even with `anthropic/claude-3.5-sonnet:beta`, the cost is still higher compared to using the Anthropic API directly. It's unfortunate that Anthropic's rate limits force me to rely on OpenRouter.

> @nishantg96 Prompt caching is working for me on v2.1.4 for `anthropic/claude-3.5-sonnet:beta` but not for `anthropic/claude-3.5-sonnet`

**Comment by saoudrizwan** [comment] 2024-12-01 01:51
This issue was fixed in 2.1.5, thank you for reporting!

**Closed by saoudrizwan** 2024-12-01 01:51 UTC
Labels: bug
