### ISSUE TITLE
BIG PROBLEM WITH CODE  truncation BIG probel

### ISSUE THREAD

**Issue by dassodev** [cline/cline#810] opened 2024-11-22 15:56 UTC
### Which API Provider are you using?

Anthropic

### Which Model are you using?

Claude 3.5 Sonnet

### What happened?

always truncation code eating token like never before

### Steps to reproduce

1.
2.
3.

**Comment by saoudrizwan** [comment] 2024-11-22 23:26
OpenAI just released a new API featured called [predicted outputs](https://platform.openai.com/docs/guides/latency-optimization#use-predicted-outputs) that would fix this issue entirely. It essentially spits out the tokens its read before and only has to "think" about new tokens (the new edits to the file), making the edit faster and more reliable without the code truncation. The issue is that this API is very rudimentary and limited (doesn't allow images, only works with gpt4o, etc) so it doesn't fit as nicely into Cline as I'd like. I'm hoping Anthropic comes out with their version of this API soon (which they've pre-released in Zed, called [Fast Edit Mode](https://www.youtube.com/watch?v=6CCuyTMhZKw)), so I can add it to Cline ASAP and fix this problem.

Pls join the [discord](https://discord.gg/cline) for updates about this, and thank you for bearing with me in the meantime 🙏

**Closed by saoudrizwan** 2024-11-22 23:26 UTC
Labels: bug

**Comment by dassodev** [comment] 2025-01-13 09:09
—
hello dear i have this problem with deepseek it first run and call two times the API then always stuck why is that
